---
name: Biblio-SIP2
version: 0.03
author:
  - 'Paul Hoffman <paul@flo.org>'
abstract: SIP2 self-check interface for integrated library systems
license: perl_5
resources:
  license: http://dev.perl.org/licenses/
requires:
  IO::Socket: 0
build_requires:
  Module::Build: 0
  Test::More: 0
generated_by: Module::Build version 0.2807
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
